DROP TABLE IF EXISTS [Devices];

CREATE TABLE [Devices] (
  [Id] INTEGER PRIMARY KEY AUTOINCREMENT,
  [RingId] INTEGER NOT NULL,
  [SiteId] INTEGER NOT NULL,
  [DeviceTypeId] INTEGER NULL,
  [Descrption] TEXT NOT NULL,
  [DeviceId] TEXT NULL,
  [Kind] TEXT NOT NULL,
  FOREIGN KEY ([SiteId]) REFERENCES [Sites] ([Id]) ON DELETE NO ACTION ON UPDATE NO ACTION
);